//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dev2Tools.API.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NGTSLOB_dev2Entities : DbContext
    {
        public NGTSLOB_dev2Entities()
            : base("name=NGTSLOB_dev2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_EMPR_EMP> TBL_EMPR_EMP { get; set; }
        public virtual DbSet<TBL_EMPR_LIAB_PERIOD_ELP> TBL_EMPR_LIAB_PERIOD_ELP { get; set; }
        public virtual DbSet<TBL_TAX_RATE_TRA> TBL_TAX_RATE_TRA { get; set; }
        public virtual DbSet<TBL_WAGE_RPT_WRE> TBL_WAGE_RPT_WRE { get; set; }
    }
}
