//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dev2Tools.API.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_WAGE_RPT_WRE
    {
        public long WRE_ID { get; set; }
        public long REF_ID_WAGE_RPT_METHD { get; set; }
        public int WRE_QTR { get; set; }
        public int WRE_YR { get; set; }
        public decimal WRE_GROSS_WAGES { get; set; }
        public string WRE_CHRG_INCORRECT_PENLTY_FLAG { get; set; }
        public long REF_ID_WAGE_RPT_STATUS { get; set; }
        public decimal WRE_OUT_OF_STATE_WAGES { get; set; }
        public int WRE_ERROR_COUNT { get; set; }
        public System.DateTime WRE_RECVD_DATE { get; set; }
        public Nullable<long> EMP_ID { get; set; }
        public string WRE_OUT_OF_STATE_EMPR_NAME { get; set; }
        public long REF_ID_RPT_TYPE { get; set; }
        public string WRE_WAGE_IMBALNC_FLAG { get; set; }
        public string WRE_MISSING_CORP_OFFICER_FLAG { get; set; }
        public long USR_LAST_MODFD_BY { get; set; }
        public System.DateTime WRE_LAST_MODFD_DATE { get; set; }
        public long BTA_ID { get; set; }
        public int WRE_RPTD_ORDER { get; set; }
        public string WRE_DUPLICATE_FLAG { get; set; }
        public Nullable<System.DateTime> WRE_PROCESS_DATE { get; set; }
    
        public virtual TBL_EMPR_EMP TBL_EMPR_EMP { get; set; }
    }
}
