//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dev2Tools.API.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_EMPR_LIAB_PERIOD_ELP
    {
        public long ELP_ID { get; set; }
        public System.DateTime ELP_LIAB_START_DATE { get; set; }
        public Nullable<System.DateTime> ELP_LIAB_END_DATE { get; set; }
        public Nullable<long> REF_ID_REINSTATE_CHNG_REASON { get; set; }
        public long EMP_ID { get; set; }
        public Nullable<long> REF_ID_LIAB_INACTV_REASON { get; set; }
        public string ELP_TITLE { get; set; }
        public string ELP_NAME { get; set; }
        public string ELP_PHONE { get; set; }
        public string ELP_PHONE_EXTENSION { get; set; }
        public Nullable<long> REF_ID_LIAB_TYPE { get; set; }
        public long USR_LAST_MODFD_BY { get; set; }
        public System.DateTime ELP_LAST_MODFD_DATE { get; set; }
        public long BTA_ID { get; set; }
        public Nullable<System.DateTime> ELP_INACTV_DTS_DATE { get; set; }
        public Nullable<System.DateTime> ELP_ACTIVATION_DATE { get; set; }
        public Nullable<long> REF_ID_LIAB_CHNG_REASON { get; set; }
    
        public virtual TBL_EMPR_EMP TBL_EMPR_EMP { get; set; }
    }
}
