//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dev2Tools.API.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_TAX_RATE_TRA
    {
        public long TRA_ID { get; set; }
        public Nullable<decimal> TRA_GRADTD_SOCIAL_COST_FACTR { get; set; }
        public Nullable<decimal> TRA_SOLVENCY_SURCHRG { get; set; }
        public Nullable<decimal> TRA_TOT_TAX_RATE { get; set; }
        public Nullable<decimal> TRA_UI_LIMIT_REDUCTION { get; set; }
        public Nullable<decimal> TRA_UI_TAX_RATE { get; set; }
        public Nullable<decimal> TRA_DELQNT_TAX_RATE { get; set; }
        public Nullable<long> TRC_ID { get; set; }
        public Nullable<decimal> TRA_EMERGENCY_EXCESS_TAX { get; set; }
        public Nullable<decimal> TRA_RESERVE_ACCT_BALNC { get; set; }
        public Nullable<decimal> TRA_BNFT_RATIO { get; set; }
        public Nullable<decimal> TRA_RESERVE_RATIO { get; set; }
        public Nullable<decimal> TRA_CNTRBNS_PD { get; set; }
        public Nullable<decimal> TRA_MIN_MAX_CPP { get; set; }
        public Nullable<decimal> TRA_PREVIOUS_TAC { get; set; }
        public long TTP_ID { get; set; }
        public Nullable<long> REF_ID_ASGNMN_METHD { get; set; }
        public Nullable<long> REF_ID_SUB_ASGNMN_METHD { get; set; }
        public long REF_ID_EMPR_QUALIFICATION { get; set; }
        public long USR_LAST_MODFD_BY { get; set; }
        public System.DateTime TRA_LAST_MODFD_DATE { get; set; }
        public long BTA_ID { get; set; }
        public Nullable<decimal> TRA_PROPOSED_TAX_RATE { get; set; }
    }
}
