//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dev2Tools.API.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_TAX_RPT_TRE
    {
        public long TRE_ID { get; set; }
        public Nullable<long> REF_ID_TAX_RPT_METHD { get; set; }
        public int TRE_QTR { get; set; }
        public int TRE_YR { get; set; }
        public System.DateTime TRE_RECVD_DATE { get; set; }
        public decimal TRE_GROSS_WAGES { get; set; }
        public Nullable<decimal> TRE_EXCESS_WAGES { get; set; }
        public Nullable<decimal> TRE_OUT_OF_STATE_WAGES { get; set; }
        public decimal TRE_TAXABLE_WAGES { get; set; }
        public string TRE_INCORRECT_WAGE_RPT_FLAG { get; set; }
        public string TRE_MISSING_WAGE_RPT_FLAG { get; set; }
        public long REF_ID_TAX_RPT_STATUS { get; set; }
        public int TRE_ERROR_COUNT { get; set; }
        public Nullable<long> EMP_ID { get; set; }
        public Nullable<long> AED_ID_SOURCE { get; set; }
        public Nullable<long> WRE_ID_SOURCE { get; set; }
        public Nullable<System.DateTime> TRE_SPLIT_DATE { get; set; }
        public Nullable<long> REF_ID_AMMENDED_REASON { get; set; }
        public string TRE_PENLTY_LEVEL_UPDT { get; set; }
        public Nullable<long> REF_ID_PENLTY_OCCURANCE_LEVEL { get; set; }
        public string TRE_INCORRECT_FORMAT_PENLTY_FL { get; set; }
        public string TRE_NO_PAYRL_THIS_QTR { get; set; }
        public Nullable<long> REF_ID_PEO_PENLTY_OCCURANCE_LE { get; set; }
        public long REF_ID_RPT_TYPE { get; set; }
        public long USR_LAST_MODFD_BY { get; set; }
        public System.DateTime TRE_LAST_MODFD_DATE { get; set; }
        public long BTA_ID { get; set; }
        public Nullable<System.DateTime> TRE_MISSINGWAGE1_DATE { get; set; }
        public Nullable<System.DateTime> TRE_MISSINGWAGE2_DATE { get; set; }
        public Nullable<decimal> TRE_EXER_STOCK_OPTNS { get; set; }
        public Nullable<decimal> TRE_EXMPT_CORP_OFFICER_EARNING { get; set; }
        public Nullable<long> TRE_EXMPT_CORP_OFFICER_COUNT { get; set; }
        public int TRE_RPTD_ORDER { get; set; }
        public string TRE_DUPLICATE_FLAG { get; set; }
        public string TRE_CONFIRMATION_NBR { get; set; }
        public Nullable<long> CEF_ID_PREPARER { get; set; }
        public Nullable<long> CEF_ID_TAX_SPECIALIST { get; set; }
        public Nullable<System.DateTime> TRE_PROCESS_DATE { get; set; }
        public Nullable<decimal> TRE_PRED_TAXABLE_WAGES { get; set; }
        public Nullable<decimal> TRE_SUB_TAXABLE_WAGES { get; set; }
        public Nullable<decimal> TRE_OUT_OF_STATE_WAGE_TAXABLE { get; set; }
        public Nullable<decimal> TRE_WA_EXCESS_WAGES { get; set; }
        public Nullable<decimal> TRE_PRED_ALLOWED { get; set; }
        public Nullable<decimal> TRE_SUB_ALLOWED { get; set; }
        public Nullable<decimal> TRE_OSW_ALLOWED { get; set; }
    
        public virtual TBL_EMPR_EMP TBL_EMPR_EMP { get; set; }
        public virtual TBL_WAGE_RPT_WRE TBL_WAGE_RPT_WRE { get; set; }
    }
}
