//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dev2Tools.API.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ADDTL_BUSNS_NAME_ABN
    {
        public long ABN_ID { get; set; }
        public string ABN_ADDTL_BUSNS_NAME { get; set; }
        public long REF_ID_ADDTL_BUSNS_NAME_TYPE { get; set; }
        public long REF_ID_ADDTL_BUSNS_NAME_STATUS { get; set; }
        public long EMP_ID { get; set; }
        public System.DateTime ABN_EFCTV_DATE { get; set; }
        public Nullable<System.DateTime> ABN_EXPIRTN_DATE { get; set; }
        public long USR_LAST_MODFD_BY { get; set; }
        public System.DateTime ABN_LAST_MODFD_DATE { get; set; }
        public long BTA_ID { get; set; }
    
        public virtual TBL_EMPR_EMP TBL_EMPR_EMP { get; set; }
    }
}
